<nav class="navbar navbar-default">
	<div class="container-fluid">

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="/"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></a></li>
				<li><a href="/my_shows.php">My Shows</a></li>
			</ul>
			<form class="navbar-form navbar-right" role="search" action="/search_shows.php">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search" name="search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
		</div>

	</div>
</nav>
