<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">

		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?=$previous_month?>">
				<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			</a>

			<a class="navbar-brand" href="#"><?=$month?></a>

			<a class="navbar-brand" href="<?=$next_month?>">
				<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			</a>

			<a class="navbar-brand hidden-md" href="javascript:scroll_to('.today')">Today</a>

		</div>

		<div class="collapse navbar-collapse" id="bs-collapse">
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="/my_shows.php">My Shows</a></li>
				<li><a class="navbar-brand" href="?recache_kickass=1">Recache Kickass</a></li>
			</ul>
			<form class="navbar-form navbar-right" role="search" action="/search_shows.php">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search" name="search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
		</div>
	</div>
</nav>